import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";

// Dev builds land straight in the vault so `npm run dev` + an Obsidian reload
// picks them up. Production builds stay in the repo root for release.
//
// The destination is per-machine, so it is not committed. It comes from the
// VAULT_PLUGIN_DIR environment variable, or from a gitignored
// `.vault-plugin-dir` file holding the same path — the file means the usual
// `npm run dev` keeps working without exporting anything first.
//
// Missing, a dev build fails loudly here rather than silently writing to the
// repo and leaving you wondering why Obsidian never picked the change up.
const DIR_FILE = ".vault-plugin-dir";
const VAULT_PLUGIN_DIR =
	process.env.VAULT_PLUGIN_DIR?.trim() ||
	(existsSync(DIR_FILE) ? readFileSync(DIR_FILE, "utf8").trim() : "");

if (!prod && !VAULT_PLUGIN_DIR) {
	console.error(
		`Nowhere to put the dev build: no VAULT_PLUGIN_DIR and no ${DIR_FILE}.\n\n` +
			"Point it at your vault's plugin folder, either way:\n" +
			`  echo "$HOME/Documents/MyVault/.obsidian/plugins/home-tasks" > ${DIR_FILE}\n` +
			'  export VAULT_PLUGIN_DIR="$HOME/Documents/MyVault/.obsidian/plugins/home-tasks"\n\n' +
			"Or run `npm run build` to build into the repo root instead.",
	);
	process.exit(1);
}

const outdir = prod ? "." : VAULT_PLUGIN_DIR;

if (!existsSync(outdir)) mkdirSync(outdir, { recursive: true });

/** Keep manifest.json and styles.css beside main.js wherever it lands. */
const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			for (const f of ["manifest.json", "styles.css"]) {
				if (existsSync(f) && join(outdir, f) !== join(".", f)) {
					copyFileSync(f, join(outdir, f));
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// rrule imports luxon only for tzid support, which floating all-day
		// rules never reach. Marking it external keeps it out of the bundle.
		"luxon",
		...builtins,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: join(outdir, "main.js"),
	minify: prod,
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
